name: BierOfen
main: de.bierofen.BierOfen
version: 2.0.0
api-version: 1.20
author: RicoDessau
website: https://biernetzwerk.de

commands:
  bierofen:
    description: Öffnet die Upgrade-GUI.
    usage: /bierofen
    permission: bierofen.use

  bieradmin:
    description: Öffnet die Admin-GUI.
    usage: /bieradmin
    permission: bierofen.admin

  bierwiki:
    description: Öffnet die Wiki-GUI.
    usage: /bierwiki
    permission: bierofen.wiki

permissions:
  bierofen.use:
    default: true

  bierofen.admin:
    default: op

  bierofen.wiki:
    default: true
