name: BierOfen
version: 2.0.1
main: de.bierofen.BierOfen
api-version: 1.20
author: RicoDessau

commands:
  bierofen:
    description: Öffnet die Upgrade-GUI
  bieradmin:
    description: Öffnet die Admin-GUI
  bierwiki:
    description: Öffnet die Wiki-GUI
